package api;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 * A autogenerated class from Swagger that sets the path for the api
 * @author Swagger
 */
@ApplicationPath("/api")
public class RestApplication extends Application {
}
